spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/is-dev-oct-6
    username: postgres
    password: Postgres@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
    #ddl-auto: update

aws:
  s3:
    accessKey: # Access Key
    secretKey: # Secret Key
    bucket: sb-awss3-demo
    region: us-east-1
